### ISSUE TITLE
Layout problems iOS (iPhone 11)

### ISSUE THREAD

**Issue by SonWu** [mochreach/chords#1]
![IMG_0986](https://user-images.githubusercontent.com/100833138/156524184-6d699677-a6b1-4ff6-bc94-67a1751da993.PNG)

**Comment by ChrisWellsWood** [comment]
Hi @SonWu, I think I've fixed this now. I've pushed the code and released a new build (v1.0.1). Could you give it a try and let me know if it works for you?

**Comment by SonWu** [comment]
Great job! It looks fine now 👍

**Comment by SonWu** [comment]
PS: Is it even possible to implement triggering the chords from the keyboard?

**Comment by ChrisWellsWood** [comment]
Yes, definitely, although there might be a tad of latency. It'll take a bit of work though and there's a weird problem that you can't change the octave on the performance track keyboard, which makes it more complex. I'll close this issue and make a new one regarding this.

**Comment by SonWu** [comment]
nice, thanks
